// Generated by CoffeeScript 1.7.0
(function() {
  var castConnection;

  castConnection = new CastConnection();

  castConnection.connect(function(data) {
    return castConnection.requestSession(function(castMedia) {
      var url;
      url = 'https://s3.amazonaws.com/roysfunfun/ghostbuster_ringtone.mp3';
      return castMedia.load({
        url: url,
        contentType: 'audio/mpeg'
      }, function() {
        document.getElementsByClassName('pause')[0].addEventListener('click', function(ev) {
          return castMedia.pause();
        });
        document.getElementsByClassName('play')[0].addEventListener('click', function(ev) {
          return castMedia.play();
        });
        return document.getElementsByClassName('exit')[0].addEventListener('click', function(ev) {
          return castMedia.quit();
        });
      });
    });
  });

}).call(this);
