// Generated by CoffeeScript 1.7.1
(function() {
  var castAway;

  castAway = window.castAway = new CastAway({
    applicationID: "8D5CA342",
    namespace: "urn:x-cast:json"
  });

  castAway.on("receivers:available", function() {
    console.log("receivers available");
    return $("#cast").click(function(ev) {
      ev.preventDefault();
      console.log("requesting session");
      return castAway.requestSession({
        success: function(session) {
          console.log("Got session", session);
          window.session = session;
          $("#start-panel").hide();
          $("#message-panel").show();
          return $("#send-message").click(function(e) {
            var val;
            val = $("#message").val();
            console.log("Sending " + val);
            $("#message").val("");
            return session.send("displayMessage", {
              message: val
            }, function(err, data) {
              if (err) {
                return console.log("error", err);
              } else {
                return console.log("success", data);
              }
            });
          });
        },
        error: function() {
          return console.log("Error", arguments);
        }
      });
    });
  });

  castAway.initialize({
    success: function(data) {
      return console.log("initialized", data);
    },
    error: function(data) {
      return console.log("error initialized", data);
    }
  });

}).call(this);
