// Generated by CoffeeScript 1.7.0
(function() {
  var attachMediaControls, castAway, castEl;

  castAway = new CastAway({
    namespace: "sample.test.default_media.receiver"
  });

  castAway.on('receivers:available', function() {});

  castAway.on('receivers:unavailable', function() {});

  castAway.on('initialize:error', function() {});

  castAway.on('session:release', function() {});

  castAway.initialize();

  castEl = document.getElementsByClassName('cast')[0];

  castEl.addEventListener('click', function(ev) {
    return castAway.createSession(function(receiver) {
      var media;
      media = {
        url: 'https://s3.amazonaws.com/roysfunfun/ghostbuster_ringtone.mp3',
        contentType: 'audio/mpeg'
      };
      console.log(receiver);
      return receiver.load(media, {
        success: function(controls) {
          return attachMediaControls(receiver, controls);
        },
        error: function(data) {}
      });
    });
  });

  attachMediaControls = function(receiver, controls) {
    var pauseEl, playEl, releaseEl;
    pauseEl = document.getElementsByClassName('pause')[0];
    pauseEl.addEventListener('click', function(ev) {
      return controls.pause();
    });
    playEl = document.getElementsByClassName('play')[0];
    playEl.addEventListener('click', function(ev) {
      return controls.play();
    });
    releaseEl = document.getElementsByClassName('release')[0];
    return releaseEl.addEventListener('click', function(ev) {
      return castAway.getReceiver({
        success: function(receiver) {
          return receiver.release();
        }
      });
    });
  };

}).call(this);
