// Generated by CoffeeScript 1.7.1
(function() {
  var MediaControls,
    __slice = [].slice;

  MediaControls = (function() {
    function MediaControls(session) {
      this.session = session;
      if (!this.session) {
        throw "No session passed";
      }
      if (!chrome.cast) {
        throw "chrome.cast namespace not found";
      }
      this.cast = chrome.cast;
    }

    MediaControls.prototype.play = function(success, error) {
      return this.session.play(null, function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return typeof success === "function" ? success.apply(null, args) : void 0;
      }, function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return typeof error === "function" ? error.apply(null, args) : void 0;
      });
    };

    MediaControls.prototype.pause = function(success, error) {
      return this.session.pause(null, function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return typeof success === "function" ? success.apply(null, args) : void 0;
      }, function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return typeof error === "function" ? error.apply(null, args) : void 0;
      });
    };

    MediaControls.prototype.stop = function(success, error) {
      return this.session.stop(null, function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return typeof success === "function" ? success.apply(null, args) : void 0;
      }, function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return typeof error === "function" ? error.apply(null, args) : void 0;
      });
    };

    MediaControls.prototype.seek = function(time, success, error) {
      var seekRequest;
      seekRequest = this.cast.session.SeekRequest(time);
      return this.session.seek(seekRequest, function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return typeof success === "function" ? success.apply(null, args) : void 0;
      }, function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return typeof error === "function" ? error.apply(null, args) : void 0;
      });
    };

    return MediaControls;

  })();

  module.exports = MediaControls;

}).call(this);
